apiVersion: v1
kind: Service
metadata:
  name: {{ include "idlehands.fullname" . }}-web
  labels:
    {{- include "idlehands.labels" . | nindent 4 }}
    app: {{ include "idlehands.fullname" . }}-web
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: {{ include "idlehands.fullname" . }}-web
