{{- range $worker := .Values.rails.workers }}
{{- $fullName := include "eve-rails-application.fullname" $ -}}
{{- with $ -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-worker-{{ $worker.name }}
  labels:
    {{- include "eve-rails-application.labels" $ | nindent 4 }}
    app: {{ $fullName }}-worker-{{ $worker.name }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ $worker.replicaCount }}
  {{- end }}
  {{- if .Values.revisionHistoryLimit }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ $fullName }}-worker-{{ $worker.name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "eve-rails-application.selectorLabels" $ | nindent 8 }}
        app: {{ $fullName }}-worker-{{ $worker.name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "eve-rails-application.serviceAccountName" $ }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $fullName }}-worker-{{ $worker.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["bundle", "exec", "sidekiq", {{- range $worker.queues }}"-q", "{{ . }}", {{- end }}"-c", "{{ $worker.maxThreads }}"]
          env:
            - name: RACK_ENV
              value: {{ .Values.rails.environment }}
            - name: RAILS_LOG_TO_STDOUT
              value: 'true'
            - name: RAILS_ENV
              value: {{ .Values.rails.environment }}
            - name: RAILS_MAX_THREADS
              value: {{ $worker.maxThreads | quote }}
          {{- if .Values.rails.envSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.rails.envSecret }}
          {{- end }}
          ports:
            - name: http
              containerPort: 7433
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            timeoutSeconds: 5
          lifecycle:
            preStop:
              exec:
                command: ["bin/sidekiq_quiet"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      initContainers:
        - name: {{ $fullName }}-worker-{{ $worker.name }}-init
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["bundle", "exec", "rails", "db:abort_if_pending_migrations"]
          env:
            - name: RAILS_LOG_TO_STDOUT
              value: 'true'
            - name: RAILS_ENV
              value: {{ .Values.rails.environment }}
          {{- if .Values.rails.envSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.rails.envSecret }}
          {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      terminationGracePeriodSeconds: 60
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}
{{- end }}
