apiVersion: v1
kind: Service
metadata:
  name: {{ include "eve-member-mailer.fullname" . }}-web
  labels:
    {{- include "eve-member-mailer.labels" . | nindent 4 }}
    app: {{ include "eve-member-mailer.fullname" . }}-web
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: {{ include "eve-member-mailer.fullname" . }}-web
